[package]
name = "boulette"
version = "0.2.0"
edition = "2021"

[dependencies]
bon = "3.3.2"
clap = { version = "4.5.23", features = ["derive"] }
gethostname = "0.5.0"
inquire = "0.7.5"
miette = { version = "7.4.0", features = ["fancy"] }
owo-colors = "4.1.0"
rand = "0.8.5"
