[toolchain]
channel = "stable"
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "wasm32-unknown-unknown",
]
components = ["rust-src", "rust-analyzer"]
profile = "default"
